version: "3"

services:
  deepseek2api:
    container_name: deepseek2api
    image: iidamie/deepseek2api:latest
    restart: always
    ports:
      - "5001:5001"
    volumes:
      - "./config.json:/app/config.json"